<tr class="setting-verificationlist" id="VerificationID_<?php echo $wo['verification']['id']?>" data_selected="<?php echo $wo['verification']['id'] ?>">
   <td><input type="checkbox" id="check-data-<?php echo $wo['verification']['id'] ?>" class="delete-checkbox filled-in"><label for="check-data-<?php echo $wo['verification']['id'] ?>"></label></td>
   <td><?php echo $wo['verification']['id']?> </td>
   <td>
      <a href="../@<?php echo $wo['verification']['request_from']['username']; ?>" target="_blank">
      <img src="<?php echo GetMedia( $wo['verification']['request_from']['avater'])?>" class="setting-avatar" alt=" Profile Picture">
      <?php
      echo $wo['verification']['request_from']['first_name'] . ' ' . $wo['verification']['request_from']['last_name']; ?>
      </a>
   </td>
   <td>
      <button type="button" data-toggle="modal" class="btn bg-info admn_table_btn toggle-verification-request" data-target="#review-verif-request-info-<?php echo $wo['verification']['id']; ?>">Show Info</button>
   <td>
      <button onclick="Wo_Verify(<?php echo $wo['verification']['request_from']['id']?>,<?php echo $wo['verification']['id']?>,'hide')" type="button" class="btn bg-success admn_table_btn">Verify</button>

      <button onclick="Wo_DeleteVerification(<?php echo $wo['verification']['id']?>,'hide')" type="button" class="btn bg-danger admn_table_btn">Ignore</button>
   </td>
</tr>
<div class="modal fade" id="review-verif-request-info-<?php echo $wo['verification']['id']; ?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Verification Info</h5>
         </div>
         <div class="modal-body">
            <div class="row">
               <?php if (!empty($wo['verification']['passport'])) { ?>
               <div class="col-md-6">
                  <a href="<?php echo GetMedia($wo['verification']['passport']); ?>" class="image-popup-gallery-item-<?php echo $wo['verification']['id']; ?>">
                     <div class="image-hover">
                        <img src="<?php echo GetMedia($wo['verification']['passport']); ?>" class="rounded" alt="image" style="width: 100%;min-height: 200px;max-height: 200px;">
                        <div class="image-hover-body rounded">
                           <div><h4 class="mb-2">Passport</h4></div>
                        </div>
                     </div>
                  </a>
               </div>
               <?php } ?>
               <?php if (!empty($wo['verification']['photo'])) { ?>
               <div class="col-md-6">
                  <a href="<?php echo GetMedia($wo['verification']['photo']); ?>" class="image-popup-gallery-item-<?php echo $wo['verification']['id']; ?>">
                     <div class="image-hover">
                        <img src="<?php echo GetMedia($wo['verification']['photo']); ?>" class="rounded" alt="image" style="width: 100%;min-height: 200px;max-height: 200px;">
                        <div class="image-hover-body rounded">
                           <div><h4 class="mb-2">Photo</h4></div>
                        </div>
                     </div>
                  </a>
               </div>
               <?php } ?>
               <?php if (!empty($wo['verification']['request_from']['snapshot'])) { ?>
               <div class="col-md-6">
                  <a href="<?php echo GetMedia($wo['verification']['request_from']['snapshot']); ?>" class="image-popup-gallery-item-<?php echo $wo['verification']['id']; ?>">
                     <div class="image-hover">
                        <img src="<?php echo GetMedia($wo['verification']['request_from']['snapshot']); ?>" class="rounded" alt="image" style="width: 100%;min-height: 200px;max-height: 200px;">
                        <div class="image-hover-body rounded">
                           <div><h4 class="mb-2">Snapshot</h4></div>
                        </div>
                     </div>
                  </a>
               </div>
               <?php } ?>
            </div>
            <br>
            <p class="mb-1"><span class="badge bg-success-bright text-success">Name</span></p>
            <p><?php echo $wo['verification']['user_name']; ?></p>
            <p class="mb-1"><span class="badge bg-info-bright text-info">Message</span></p>
            <p><?php echo $wo['verification']['message']; ?></p>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
         </div>
      </div>
   </div>
</div>
<script type="text/javascript">
   $(document).ready(function() {
      $('.image-popup-gallery-item-<?php echo $wo['verification']['id']; ?>').magnificPopup({
           type: 'image',
           gallery: {
               enabled: true
           },
           zoom: {
               enabled: true,
               duration: 300,
               easing: 'ease-in-out',
               opener: function(openerElement) {
                   return openerElement.is('img') ? openerElement : openerElement.find('img');
               }
           }
       });
   });
</script>