<tr class="user-list" id="ReceiptID_<?php echo $wo['mediafilelist']->id?>" data-receipt-id="<?php echo $wo['mediafilelist']->id?>">
	<td>
		<a href="<?php echo $wo['site_url'] . '/@' . $wo['mediafilelist']->username; ?>" target="_blank">
			<img src="<?php echo GetMedia($wo['mediafilelist']->avater);?>" class="setting-avatar rounded-circle mr-1" alt="<?php echo $wo['mediafilelist']->username;?> Profile Picture"> <?php echo $wo['mediafilelist']->username; ?>
		</a>
	</td>
	<td><span class="ajax-time"><?php echo Time_Elapsed_String(strtotime($wo['mediafilelist']->created_at));?></span></td>
	<td>
		<a class="image-popup-gallery-item-<?php echo $wo['mediafilelist']->id; ?> btn bg-info admn_table_btn admn-mng-bnk-rct" href="<?php echo GetMedia($wo['mediafilelist']->snapshot); ?>">
			<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M3,22L4.5,20.5L6,22L7.5,20.5L9,22L10.5,20.5L12,22L13.5,20.5L15,22L16.5,20.5L18,22L19.5,20.5L21,22V2L19.5,3.5L18,2L16.5,3.5L15,2L13.5,3.5L12,2L10.5,3.5L9,2L7.5,3.5L6,2L4.5,3.5L3,2M18,9H6V7H18M18,13H6V11H18M18,17H6V15H18V17Z"></path></svg> <img src="<?php echo GetMedia($wo['mediafilelist']->snapshot); ?>" class="card-img-top">Show Info
		</a>
	</td>
	<td>
		<?php if((int)$wo['mediafilelist']->approved_at == 0){?>
			<button type="button" class="btn bg-success admn_table_btn" onclick="Wo_ApproveUser(<?php echo $wo['mediafilelist']->id?>,'<?php echo $wo['mediafilelist']->snapshot?>','hide');">Approve</button>
			<button type="button" class="btn bg-danger admn_table_btn" onclick="Wo_DeleteUser(<?php echo $wo['mediafilelist']->id?>,'<?php echo $wo['mediafilelist']->snapshot?>','hide');">Delete</button>
		<?php } else{ ?>
			<b style="color:darkgreen;">Approved <?php echo Time_Elapsed_String($wo['mediafilelist']->approved_at);?></b>
		<?php }?>
	</td>
</tr>

<script type="text/javascript">
   $(document).ready(function() {
      $('.image-popup-gallery-item-<?php echo $wo['mediafilelist']->id; ?>').magnificPopup({
           type: 'image',
           gallery: {
               enabled: true
           },
           zoom: {
               enabled: true,
               duration: 300,
               easing: 'ease-in-out',
               opener: function(openerElement) {
                   return openerElement.is('img') ? openerElement : openerElement.find('img');
               }
           }
       });
   });
</script>