<tr class="setting-stickerlist" id="StickerID_<?php echo $wo['stickerlist']['id']?>" data-sticker-id="<?php echo $wo['stickerlist']['id']?>" data_selected="<?php echo $wo['stickerlist']['id']?>">
  <td><input type="checkbox" id="check-data-<?php echo $wo['stickerlist']['id']?>" class="delete-checkbox filled-in"><label for="check-data-<?php echo $wo['stickerlist']['id']?>"></label></td>
   <td><?php echo $wo['stickerlist']['id']?></td>
   <td>
        <a class="image-popup" href="<?php echo GetMedia($wo['stickerlist']['file']); ?>">
            <img src="<?php echo GetMedia( $wo['stickerlist']['file'] ); ?>" class="setting-avatar" alt="Sticker Picture">
        </a>
   </td>
   <td><?php echo ($wo['stickerlist']['is_pro'] == "0") ? 'No' : 'Yes';?></td>
   <td>
     <div class="ajax-time" title="<?php echo date('c',$wo['stickerlist']['time']); ?>">
         <?php echo ( $wo['stickerlist']['created_at'] !== null ? Time_Elapsed_String(strtotime($wo['stickerlist']['created_at'])) : '-');?>
     </div>
   </td>
   <td>
    <button class="btn bg-danger admn_table_btn" onclick="Wo_DeleteSticker(<?php echo $wo['stickerlist']['id']?>,'hide');">DELETE</button>
   </td>
</tr>