<tr id="<?php echo $wo['gender_key'];?>" data_selected="<?php echo $wo['gender_key'] ?>">
  <td><input type="checkbox" id="check-data-<?php echo $wo['gender_key'] ?>" class="delete-checkbox filled-in"><label for="check-data-<?php echo $wo['gender_key'] ?>"></label></td>
   <td><?php echo $wo['gender_id'];?></td>
   <td><?php echo $wo['gender_key'];?></td>
   <td id="edit_<?php echo $wo['gender_key'];?>"><?php echo $wo['gender'];?></td>
    <td><?php $gender_option = $db->where('ref','gender')->where('id',$wo['gender_key'])->getOne('langs',array('options'));?>

        <div class="form-group">
            <input onclick="Wo_FreeGenderEnable('<?php echo $wo['gender_key'];?>');" type="radio" id="gender_free_<?php echo $wo['gender_key'];?>_enabled" name="gender_free_<?php echo $wo['gender_key'];?>" value="1" <?php echo ( $gender_option['options'] !== null ) ? 'checked=""' : '';?>>
            <label for="gender_free_<?php echo $wo['gender_key'];?>_enabled">Enabled</label>
            <input onclick="Wo_FreeGenderDisable('<?php echo $wo['gender_key'];?>');" type="radio" id="gender_free_<?php echo $wo['gender_key'];?>_disabled" name="gender_free_<?php echo $wo['gender_key'];?>" value="0" <?php echo ( $gender_option['options'] !== null ) ? '' : 'checked=""';?>>
            <label for="gender_free_<?php echo $wo['gender_key'];?>_disabled" class="m-l-20">Disabled</label>
        </div>

    </td>
   <td>
      <button type="button" class="btn bg-success admn_table_btn btn-lang" data-id="<?php echo $wo['gender_key'];?>" data-toggle="modal" data-target="#defaultModal">Edit</button>
      <button onclick="Wo_DeleteGender('<?php echo $wo['gender_key'];?>','hide');" type="button" class="btn bg-danger admn_table_btn">Delete</button>
   </td>
</tr>