<div class="container-fluid">
    <div>
        <h3>CHANGELOGS</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">CHANGELOGS </li>
            </ol>
        </nav>
    </div>
    <div class="alert alert-success">Updates are provided freely for life-time if you own a valid purchase code.</div>
    <div class="row clearfix">
               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <div class="card">
                       <div class="card-body">
                           <h6 class="card-title">v1.7 <small>[21/12/2022]</small></h6>
                           <ul>
                             <li>[Added] support for PHP 8.1.*</li>
                             <li>[Added] the ability to disable a language.</li>
                             <li>[Added] webp support.</li>
                             <li>[Added] subscribe to newsletters on home page.</li>
                             <li>[Added] the ability to set minimum withdrawal amount.</li>
                             <li>[Added] new modern design for "love" theme. </li>
                             <li>[Added] deny username system.</li>
                             <li>[Added] BACKBLAZE cloud storage.</li>
                             <li>[Added] developer mode.</li>
                             <li>[Added] ffmpeg debuuger.</li>
                             <li>[Added] flutterwave payment method.</li>
                             <li>[Added] age restriction system. </li>
                             <li>[Added] system status. </li>
                             <li>[Added] Google recaptcha. </li>
                             <li>[Added] withdrawal payment methods. </li>
                             <li>[Updated] find matches system completely (backend).</li>
                             <li>[Updated] all PHP libs.</li>
                             <li>[Fixed] user can't change birthday from mobile.</li>
                             <li>[Fixed] user can't change birthday from desktop.</li>
                             <li>[Fixed] facebook and twitter links are not correct, they are reversed.</li>
                             <li>[Fixed] email sent from server didn't support HTML code.</li>
                             <li>[Fixed] some JS errros on console log.</li>
                             <li>[Fixed] male and female selection in find match page were not diselecting.</li>
                             <li>[Fixed] "Allowed E-mail Providers" was not working.</li>
                             <li>[Fixed] Agora live and video calls.</li>
                             <li>[Fixed] developer page is showing even if developer page is disabled.</li>
                             <li>[Fixed] can't upload image to messages while S3 enabled.</li>
                             <li>[Fixed] deleting users doesn't delete their data from same tables.</li>
                             <li>[Fixed] image verfication issues.</li>
                             <li>[Fixed] logging out doesn't work from admin panel.</li>
                             <li>[Fixed] day/night mode switcher problems.</li>
                             <li>[Fixed] right click + paste doesn't work in admin panel inputs.</li>
                             <li>[Fixed] SMS bugs, messagebird + msg91.</li>
                             <li>[Fixed] social media links in footer are disabled but is still shown. </li>
                             <li>[Fixed] login with VK + mail.ru</li>
                             <li>[Fixed] some php files showing on google search results.</li>
                             <li>[Fixed] "select box" custom fields not working.</li>
                             <li>[Fixed] when you try to remove a language from the admin panel, the site will be crushed.</li>
                             <li>[Fixed] for free users, you can write a message to more than 1 user.</li>
                             <li>[Fixed] private image is not working when using third party storage other than amazon.</li>
                             <li>[Fixed] If user registration is disabled in the admin panel, but social login is enabled, user can't register using social login.</li>
                             <li>[Fixed] 10+ API issues.</li>
                             <li>[Fixed] 20+ minor bugs.</li>
                           </ul>
                       </div>
                   </div>
               </div>
           </div>
    <div class="row clearfix">
               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <div class="card">
                       <div class="card-body">
                           <h6 class="card-title">v1.6.3</h6>
                           <ul>
                             <li>[Fixed] broken images on find matches page if the user had videos posted.</li>
                             <li>[Fixed] google analytics code not saving in admin panel.</li>
                             <li>[Fixed] "index" showing on meta tags on home page. </li>
                             <li>[Fixed] create article was not working if S3 is enableld.</li>
                           </ul>
                       </div>
                   </div>
               </div>
           </div>
    <div class="row clearfix">
               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <div class="card">
                       <div class="card-body">
                           <h6 class="card-title">v1.6.2</h6>
                           <ul>
                             <li>[Fixed] character limit for terms page.</li>
                             <li>[Fixed] "index" showing on home page. </li>
                             <li>[Fixed] 500 PHP error when uploading stickers. </li>
                           </ul>
                       </div>
                   </div>
               </div>
           </div>
    <div class="row clearfix">
               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <div class="card">
                       <div class="card-body">
                           <h6 class="card-title">v1.6.1</h6>
                           <ul>
                             <li>[Added] fluttewave payment method.</li>
                             <li>[Improved] design in few sections. </li>
                             <li>[Fixed] 20+ reported bugs & design issues.</li>
                             <li>[Improved] stability & speed. </li>
                           </ul>
                       </div>
                   </div>
               </div>
           </div>
    <div class="row clearfix">
               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <div class="card">
                       <div class="card-body">
                           <h6 class="card-title">v1.6</h6>
                           <ul>
                             <li>[Added] fortumo payment method.</li>
                             <li>[Added] CoinPayments payment method.</li>
                             <li>[Added] Coinbase payment method. </li>
                             <li>[Added] Aamarpay payment method. </li>
                             <li>[Added] Ngenius payment method. </li>
                             <li>[Added] currency system. </li>
                             <li>[Added] FAQs page. </li>
                             <li>[Added] HTML editor to Admin Panel -> Pages -> Manage Pages.</li>
                             <li>[Added] refund policy page. </li>
                             <li>[Added] moderators system.</li>
                             <li>[Added] linkedin social login. </li>
                             <li>[Added] ok.ru social login. </li>
                             <li>[Added] watermark on posts. </li>
                             <li>[Added] the ability to translate terms pages. </li>
                             <li>[Added] import photos from Instagram. </li>
                             <li>[Added] new APIs. </li>
                             <li>[Added] the ability to filter by country for PRO or free memebers</li>
                             <li>[Updated] docs: https://docs.quickdatescript.com/ </li>
                             <li>[Fixed] 30+ reported bugs.</li>
                             <li>[Improved] stability & speed. </li>
                           </ul>
                       </div>
                   </div>
               </div>
           </div>
     <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5</h6>
                            <li>[Added] prevent login system.</li>
                            <li>[Added] download user data from settings page.</li>
                            <li>[Added] ability to request withdrawal using bank. </li>
                            <li>[Added] 3 new payment methods, PayStack, Authorize.Net, Securionpay. </li>
                            <li>[Added] agora video & audio chat.</li>
                            <li>[Added] live streaming system. </li>
                            <li>[Added] QQ, WeChat, Discord and Mailru social login.</li>
                            <li>[Added] developer system, users can now create application and use login with system. </li>
                            <li>[Added] MessageBird, BulkSMS, Infobip, Msg91 SMS providers. </li>
                            <li>[Added] Invitation system for users and admin. </li>
                            <li>[Added] auto like system, admin can choose an account which get liked by every new user. </li>
                            <li>[Added] new APIs. </li>
                            <li>[Improved] admin panel english and desgin.</li>
                            <li>[Fixed] 30+ reported bugs.</li>
                            <li>[Improved] stability & speed. </li>
                        </div>
                    </div>
                </div>
            </div>
              <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.2</h6>
                            <li>[Added] +4 payments methods.</li>
                            <li>[Added] new admin panel, v2.</li>
                            <li>[Added] notifications system in admin panel. </li>
                            <li>[Added] new theme [love]. </li>
                            <li>[Added] new APIs.</li>
                            <li>[Fixed] 40+ reported bugs.</li>
                            <li>[Improved] stability & speed. </li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.1</h6>
                            <li>[Added] gifts page, you can view the gifts you received from other users.</li>
                            <li>[Added] ability to add, edit, remove countries from the admin panel.</li>
                            <li>[Added] ability to pay admin to unlock private photos (enable/disable).</li>
                            <li>[Added] only pro users could upload videos and pay to unlock.  (enable/disable)</li>
                            <li>[Added] credit system with daily login, earn credits by logining in in daily. </li>
                            <li>[Added] ability to submit verification docs on "start up page" on sign up  (enable/disable) </li>
                            <li>[Added] allow sign up from specific domain only for example gmail.com. </li>
                            <li>[Added] ability to block certain domain sign up like yahoo.com for example.</li>
                            <li>[Fixed] 40+ reported bugs.</li>
                            <li>[Improved] stability & speed. </li>
                        </div>
                    </div>
                </div>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4</h6>
                            <li>[Added] ability to upload videos + FFMPEG.</li>
                            <li>[Added] moderator user (admin could set what pages a specific moderator could access in the admin).</li>
                            <li>[Added] ability to lock gender after someone selects during sign up.</li>
                            <li>[Added] friend system, user can add friends / accept decline (enable / disable.)</li>
                            <li>[Added] blacklist system, block user by email, username and IP. </li>
                            <li>[Added] affiliate system, users can earn money by refrerring users. </li>
                            <li>[Added] users on home page (enable/disable). </li>
                            <li>[Added] ability to send mock emails to user who didn't login for week/month/year/ from admin panel.</li>
                            <li>[Added] ability to limit number of max photo a user can upload from admin panel (unlimited for pro user)</li>
                            <li>[Added] ability to review photos and videos by admin with (enable/disable)</li>
                            <li>[Fixed] 20+ reported bugs.</li>
                            <li>[Improved] stability & speed. </li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.3.2</h6>
                            <li>[Fixed] API issues.</li>
                            <li>[Fixed] 10+ reported bugs.</li>
                            <li>[Improved] stability & speed. </li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.3.1</h6>
                            <li>[Fixed] API issues.</li>
                            <li>[Fixed] 10+ reported bugs.</li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.3</h6>
                            <li>[Added] the ability to make the site fully free for a spasefic gender.</li>
                            <li>[Added] the ability to make site completely free.</li>
                            <li>[Added] success stories system.</li>
                            <li>[Added] blog system (only admin can create blogs). </li>
                            <li>[Added] hot or not system. </li>
                            <li>[Added] image webcam verification system.</li>
                            <li>[Added] spam warning, user won't be able to send messages for 24 hours if they were marked as spam.</li>
                            <li>[Added] one signal support. </li>
                            <li>[Fixed] few reported bugs.</li>
                            <li>[Improved] SQL indexes + speed.</li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.2.2</h6>
                            <li>[Fixed] API issues.</li>
                            <li>[Fixed] few reported bugs.</li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.2.1</h6>
                            <li>[Added] request limits for user activations in admin panel > general settings. </li>
                            <li>[Fixed] few reported bugs.</li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.2</h6>
                            <li>[Added] email notifications.</li>
                            <li>[Added] the ability to see suggestion of users living in the same country or state if there is no user from same country then other should appear. </li>
                            <li>[Added] the ability to enable disable pro system. </li>
                            <li>[Added] the ability to randomize pro users section at the moment it shows latest.</li>
                            <li>[Added] the ability to create custom pages. </li>
                            <li>[Added] the ability for users to upload private pictures, and once the user matched with them, they can see their pictures. </li>
                            <li>[Added] video / audio calls API.</li>
                            <li>[Added] the ability to create custom fields for search and profile. </li>
                            <li>[Added] the ability to turn off or on audio/video calls for pro users only or all users.</li>
                            <li>[Improved] search system.</li>
                            <li>[Improved] MySQL queries.</li>
                            <li>[Improved] site speed.</li>
                            <li>[Fixed] few reported bugs.</li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.1.2</h6>
                            <li>[Added] ads slots, now admin can add ads on 4 slots on the site.</li>
                            <li>[Improved] site speed.</li>
                            <li>[Fixed] few reported bugs.</li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.1</h6>
                            <li>[Added] video and audio calls.</li>
                            <li>[Added] fake user generator. </li>
                            <li>[Added] announcement system.</li>
                            <li>[Added] messaging approval / decline system, user can decline a message from other users.</li>
                            <li>[Added] user now can see himself in pro sidebar if he boosted.</li>
                            <li>[Added] daily like limit, user can't like more than X users per day. </li>
                            <li>[Added] bank payments system, user can pay via bank local payments.</li>
                            <li>[Added] the ability to manage genders from admin panel.</li>
                            <li>[Added] cookie law bar.</li>
                            <li>[Added] the ability for pro user to change his country, and relocate.</li>
                            <li>[Added] SMS gateaway payment using: paysera.com</li>
                            <li>[Added] the ability to switch between Miles and KM.</li>
                            <li>[Added] Maintenance mode.</li>
                            <li>[Added] Night mode.</li>
                            <li>[Added] support for RTL languges.</li>
                            <li>[Removed] landing page, user land on login page now.</li>
                            <li>[Improved] site speed.</li>
                            <li>[Fixed] few reported bugs.</li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.0</h6>
                            <li>Version 1.0 released on 2019.</li>

                        </div>
                    </div>
                </div>
            </div>
        </div>
