<tr id="<?php echo $wo['category_key'];?>" data_selected="<?php echo $wo['category_key'] ?>">
	<td><input type="checkbox" id="check-data-<?php echo $wo['category_key'] ?>" class="delete-checkbox filled-in"><label for="check-data-<?php echo $wo['category_key'] ?>"></label></td>
    <td><?php echo $wo['category_id'];?></td>
    <td id="edit_<?php echo $wo['category_key'];?>"><?php echo $wo['category'];?></td>
    <td>
        <button type="button" class="btn bg-success admn_table_btn btn-lang m-r-20" data-id="<?php echo $wo['category_key'];?>" data-toggle="modal" data-target="#defaultModal">Edit</button>
        <button onclick="Wo_DeleteCategory('<?php echo $wo['category_key'];?>','hide');" type="button" class="btn bg-danger admn_table_btn">Delete</button>
    </td>
</tr>